-- 0014: 理科(生物分野)を追加する
--
-- 13クイズ・240問。genre は rika、section は 生物。
--   細胞のつくり 13問
--   光合成と植物のはたらき 19問
--   生物の分類 20問
--   花のつくりと発生 18問
--   消化と吸収 20問
--   呼吸と血液の循環 20問
--   排出のしくみ 18問
--   刺激と反応 20問
--   生殖と細胞分裂 17問
--   遺伝 19問
--   進化と化石 16問
--   生態系と食物連鎖 18問
--   環境と生物多様性 22問
--
-- 既存のデータには一切触れない(追加のみ)。
-- 適用: npx wrangler d1 execute chishiki-quiz-db --remote --file=./migrations/0014_add_rika.sql
-- 冪等: INSERT OR IGNORE のみなので再実行しても安全。

-- クイズ 13件
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-saibou', '細胞のつくり', 'rika', '生物', 'rika/saibou/', 10, 200, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kougousei', '光合成と植物のはたらき', 'rika', '生物', 'rika/kougousei/', 10, 210, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-bunrui', '生物の分類', 'rika', '生物', 'rika/bunrui/', 10, 220, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-hana-hassei', '花のつくりと発生', 'rika', '生物', 'rika/hana-hassei/', 10, 230, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-shouka', '消化と吸収', 'rika', '生物', 'rika/shouka/', 10, 240, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kokyu-junkan', '呼吸と血液の循環', 'rika', '生物', 'rika/kokyu-junkan/', 10, 250, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-haishutsu', '排出のしくみ', 'rika', '生物', 'rika/haishutsu/', 10, 260, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-shigeki-hannou', '刺激と反応', 'rika', '生物', 'rika/shigeki-hannou/', 10, 270, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-seishoku', '生殖と細胞分裂', 'rika', '生物', 'rika/seishoku/', 10, 280, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-iden', '遺伝', 'rika', '生物', 'rika/iden/', 10, 290, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-shinka', '進化と化石', 'rika', '生物', 'rika/shinka/', 10, 300, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-seitaikei', '生態系と食物連鎖', 'rika', '生物', 'rika/seitaikei/', 10, 310, 0);
INSERT OR IGNORE INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kankyou', '環境と生物多様性', 'rika', '生物', 'rika/kankyou/', 10, 320, 0);

-- 問題 240件
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-01', '生物の体をつくる基本単位となる小さな構造を何というか。', '細胞', '細胞', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-02', '細胞の中にあり、細胞の活動を調節する部分を何というか。', '核', '細胞', '{"accept":["細胞核"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-03', '核の周りにあり、細胞のさまざまな働きが行われる部分を何というか。', '細胞質', '細胞', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-04', '細胞質の外側を包み、細胞内外の物質の出入りを調節する膜を何というか。', '細胞膜', '細胞', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-05', '植物細胞の最も外側にあり、細胞を保護して形を保つつくりを何というか。', '細胞壁', '植物細胞', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-06', '植物細胞にあり、細胞液を含む袋状のつくりを何というか。', '液胞', '植物細胞', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-07', '液胞の内部を満たしている液体を何というか。', '細胞液', '植物細胞', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-08', '緑色の植物細胞にはあるが、一般的な動物細胞にはない、光合成を行うつくりを何というか。', '葉緑体', '相違点', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-09', '植物細胞と動物細胞を顕微鏡で観察するとき、核を染めるために使う液を何というか。', '酢酸カーミン液', '観察', '{"accept":["酢酸オルセイン液"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-10', '同じ種類で、同じような働きをする細胞が集まったものを何というか。', '組織', '細胞の集まり', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-11', 'いくつかの組織が組み合わさって、特定の働きをする部分を何というか。', '器官', '細胞の集まり', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-12', '体が1個の細胞だけでできている生物を何というか。', '単細胞生物', '生物の体', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-saibou', 'q-13', '体が多数の細胞でできている生物を何というか。', '多細胞生物', '生物の体', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-01', '葉の細胞内で、光合成を行う緑色の粒状のつくりを何というか。', '葉緑体', '細胞', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-02', '葉緑体に含まれ、光合成に必要な光を吸収する緑色の色素を何というか。', '葉緑素', '細胞', '{"accept":["クロロフィル"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-03', '根の表面にあり、土の粒のすき間に入り込んで水や無機養分を吸収する細い突起を何というか。', '根毛', '根', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-04', '根から吸収した水や無機養分が通る、茎や葉の中の管を何というか。', '道管', '植物体内の移動', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-05', '葉でつくられた養分が通る、茎や葉の中の管を何というか。', '師管', '植物体内の移動', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-06', '葉の表皮にあり、二酸化炭素や酸素などの気体が出入りする小さな穴を何というか。', '気孔', '葉', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-07', '気孔をつくり、その開閉を調節している一対の細胞を何というか。', '孔辺細胞', '葉', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-08', '光合成で、植物が空気中から取り入れる気体は何か。', '二酸化炭素', '光合成', '{"accept":["炭酸ガス","CO2"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-09', '光合成で、植物が根から吸収して原料として使う物質は何か。', '水', '光合成', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-10', '光合成によってつくられ、ヨウ素液で青紫色に変化する養分は何か。', 'デンプン', '光合成', '{"accept":["澱粉"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-11', '光合成によって、植物の体内から空気中へ放出される気体は何か。', '酸素', '光合成', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-12', '葉に光が当たるとデンプンができることを確かめる実験で、葉の一部を覆うために使うものは何か。', 'アルミニウムはく', '光合成の実験', '{"accept":["アルミ箔","アルミホイル","アルミはく","アルミニウム箔"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-13', '光合成の実験の前に植物を暗い場所に置くのは、葉に残っている何を使い切らせるためか。', 'デンプン', '光合成の実験', '{"accept":["澱粉"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-14', '葉の一部をアルミニウムはくで覆って日光に当てた後、ヨウ素液で調べた。青紫色になったのは、光が当たった部分と当たらなかった部分のどちらか。', '光が当たった部分', '光合成の実験', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-15', '葉でつくられたデンプンは、そのままでは水にとけにくい。植物はデンプンを何に変えて、師管を通して運ぶか。', '糖', '養分の移動', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-16', '植物の体内の水が、水蒸気となって主に気孔から空気中へ出ていく現象を何というか。', '蒸散', '葉', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-17', '色水を吸わせた植物の茎を縦に切ると、色がつくのは道管と師管のどちらか。', '道管', '水の移動', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-18', '植物は光合成をしていない夜にも呼吸を行う。呼吸によって植物が取り入れる気体は何か。', '酸素', '呼吸', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kougousei', 'q-19', '植物が呼吸を行うのは、昼だけか、夜だけか、昼も夜もか。', '昼も夜も', '呼吸', '{"accept":["昼夜とも","一日中","昼も夜も行う"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-01', '生物を、共通点や相違点を基準にして仲間分けすることを何というか。', '分類', '生物の分類', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-02', '背骨をもつ動物をまとめて何というか。', '脊椎動物', '動物の分類', '{"accept":["せきつい動物"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-03', '背骨をもたない動物をまとめて何というか。', '無脊椎動物', '動物の分類', '{"accept":["むせきつい動物"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-04', '一生を主に水中で過ごし、えらで呼吸する脊椎動物の仲間を何というか。', '魚類', '脊椎動物', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-05', '子どもの時期を水中で過ごし、成長すると肺や皮膚で呼吸する脊椎動物の仲間を何というか。', '両生類', '脊椎動物', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-06', '体表がうろこや硬い皮膚で覆われ、肺で呼吸する脊椎動物の仲間を何というか。', 'は虫類', '脊椎動物', '{"accept":["爬虫類","はちゅう類","はちゅうるい"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-07', '体表が羽毛で覆われ、前あしが翼になっている脊椎動物の仲間を何というか。', '鳥類', '脊椎動物', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-08', '体表が毛で覆われ、子を乳で育てる脊椎動物の仲間を何というか。', '哺乳類', '脊椎動物', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-09', '体が節に分かれ、関節のあるあしをもつ無脊椎動物の仲間を何というか。', '節足動物', '無脊椎動物', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-10', '節足動物のうち、頭部・胸部・腹部の3部分に分かれ、3対のあしをもつ仲間を何というか。', '昆虫類', '節足動物', '{"accept":["昆虫"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-11', 'エビやカニのように、体が頭胸部と腹部に分かれ、あしに節がある仲間を何というか。', '甲殻類', '節足動物', '{"accept":["こうかく類"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-12', 'アサリやイカのように、節のない柔らかい体をもつ無脊椎動物の仲間を何というか。', '軟体動物', '無脊椎動物', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-13', '種子をつくってなかまをふやす植物を何というか。', '種子植物', '植物の分類', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-14', '種子が果実の中に包まれている植物を何というか。', '被子植物', '種子植物', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-15', '子房がなく、胚珠がむき出しになっている植物を何というか。', '裸子植物', '種子植物', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-16', '胞子でなかまをふやし、根・茎・葉の区別がある植物を何というか。', 'シダ植物', '植物の分類', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-17', '胞子でなかまをふやし、根・茎・葉の区別がはっきりしない植物を何というか。', 'コケ植物', '植物の分類', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-18', '発芽したときに子葉が1枚の被子植物を何というか。', '単子葉類', '被子植物', '{"accept":["単子葉植物"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-19', '発芽したときに子葉が2枚の被子植物を何というか。', '双子葉類', '被子植物', '{"accept":["双子葉植物"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-bunrui', 'q-20', 'シダ植物やコケ植物が、なかまをふやすときにつくるものを何というか。', '胞子', '植物の分類', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-01', '被子植物で、花粉をつくる雄性の生殖器官を何というか。', 'おしべ', '花のつくり', '{"accept":["雄しべ"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-02', 'おしべの先端にあり、花粉がつくられる部分を何というか。', 'やく', '花のつくり', '{"accept":["葯"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-03', '被子植物で、胚珠を含む器官を何というか。', 'めしべ', '花のつくり', '{"accept":["雌しべ"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-04', 'めしべの先端にあり、花粉がつく部分を何というか。', '柱頭', '花のつくり', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-05', 'めしべの内部にあり、胚珠を含むふくらんだ部分を何というか。', '子房', '花のつくり', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-06', '花粉が柱頭につくことを何というか。', '受粉', '植物の生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-07', '柱頭についた花粉から伸び、精細胞を胚珠へ運ぶ管を何というか。', '花粉管', '植物の生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-08', '受精後、胚珠が成長してできるものを何というか。', '種子', '植物の生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-09', '受精後、子房が成長してできるものを何というか。', '果実', '植物の生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-10', '種子の中にあり、成長すると新しい植物の体になる部分を何というか。', '胚', '種子', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-11', '同じ花のめしべの柱頭に、その花のおしべの花粉がつくことを何というか。', '自家受粉', '受粉', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-12', 'ある個体の花粉が、同じ種類の別の個体の柱頭につくことを何というか。', '他家受粉', '受粉', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-13', '魚類や両生類のように、体外で精子と卵が結合する受精を何というか。', '体外受精', '動物の生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-14', 'ヒトや鳥類のように、母体や親の体内で精子と卵が結合する受精を何というか。', '体内受精', '動物の生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-15', '魚類や鳥類のように、親の体外に卵を産み、卵から子がかえる生まれ方を何というか。', '卵生', '動物の発生', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-16', 'ヒトや多くの哺乳類のように、母体内で子が育ってから生まれる生まれ方を何というか。', '胎生', '動物の発生', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-17', '受精卵が細胞分裂を繰り返して、体の各部分がつくられていく過程を何というか。', '発生', '動物の発生', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-hana-hassei', 'q-18', 'カエルのように、幼生から成体へ成長する途中で体のつくりが大きく変化することを何というか。', '変態', '動物の発生', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-01', '口から肛門まで続き、食物が通過する一続きの器官をまとめて何というか。', '消化管', '消化器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-02', '口の中で分泌され、デンプンを分解する消化液を何というか。', 'だ液', '消化液', '{"accept":["唾液","だえき"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-03', 'だ液に含まれ、デンプンを分解する消化酵素を何というか。', 'アミラーゼ', '消化酵素', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-04', 'だ液に含まれるアミラーゼは、デンプンを主に何という糖に分解するか。', '麦芽糖', '消化', '{"accept":["マルトース","糖"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-05', '食物を一時的にため、胃液を分泌して消化を行う器官は何か。', '胃', '消化器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-06', '胃液に含まれ、タンパク質を分解する消化酵素を何というか。', 'ペプシン', '消化酵素', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-07', '胃で分泌され、ペプシンを含む消化液を何というか。', '胃液', '消化液', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-08', '肝臓でつくられ、脂肪を細かい粒にして消化しやすくする液を何というか。', '胆汁', '消化液', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-09', '胆汁をつくる器官は何か。', '肝臓', '消化器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-10', '胆汁には消化酵素が含まれているか、含まれていないか。', '含まれていない', '消化液', '{"accept":["含まれない","含まない"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-11', '胃と小腸の間にあり、胆汁やすい液が流れ込む小腸の始まりの部分を何というか。', '十二指腸', '消化器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-12', '小腸から分泌され、消化を行う消化液を何というか。', '腸液', '消化液', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-13', 'すい臓から分泌され、デンプン・タンパク質・脂肪などを消化する消化液を何というか。', 'すい液', '消化液', '{"accept":["膵液","すいえき"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-14', '栄養分の消化と吸収が主に行われる器官は何か。', '小腸', '消化器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-15', '小腸の内壁にある、表面積を大きくする細かい突起を何というか。', '柔毛', '小腸', '{"accept":["じゅうもう","絨毛"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-16', '柔毛の中に入り込んでいて、ブドウ糖やアミノ酸を取り込む細い血管を何というか。', '毛細血管', '吸収', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-17', 'デンプンが消化されてできたブドウ糖は、柔毛から血液とリンパ液のどちらに取り込まれるか。', '血液', '吸収', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-18', 'タンパク質が消化されてできたアミノ酸は、柔毛から血液とリンパ液のどちらに取り込まれるか。', '血液', '吸収', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-19', '脂肪が消化されてできた脂肪酸とモノグリセリドは、柔毛の中のどの管に取り込まれるか。', 'リンパ管', '吸収', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shouka', 'q-20', '消化されずに大腸へ送られた食物の残りから、大腸で主に吸収されるものは何か。', '水', '大腸', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-01', '細胞が栄養分と酸素を使ってエネルギーを取り出し、二酸化炭素と水を生じる働きを何というか。', '呼吸', '呼吸', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-02', '空気中から酸素を取り入れ、二酸化炭素を放出する器官は何か。', '肺', '呼吸器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-03', '鼻や口から入った空気を肺へ運ぶ、首から胸にかけての管を何というか。', '気管', '呼吸器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-04', '気管が左右に分かれたあと、肺の中へ伸びていく2本の管を何というか。', '気管支', '呼吸器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-05', '肺の中で、毛細血管に取り囲まれ、酸素と二酸化炭素の交換を行う小さな袋を何というか。', '肺胞', '呼吸器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-06', '肺胞の壁が薄く、肺胞の数が多いことで、何が効率よく行われるか。', '気体交換', '肺胞', '{"accept":["ガス交換","酸素と二酸化炭素の交換"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-07', '肺胞で、空気中から血液中へ取り込まれる気体は何か。', '酸素', '気体交換', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-08', '肺胞で、血液中から空気中へ排出される気体は何か。', '二酸化炭素', '気体交換', '{"accept":["炭酸ガス","CO2"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-09', '息を吸うとき、横隔膜は収縮して上がるか、下がるか。', '下がる', '呼吸運動', '{"accept":["下降する"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-10', '息を吐くとき、胸郭の容積は大きくなるか、小さくなるか。', '小さくなる', '呼吸運動', '{"accept":["減少する"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-11', '心臓から血液が出ていくときに通る血管を何というか。', '動脈', '血管', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-12', '全身から心臓へ血液が戻ってくるときに通る血管を何というか。', '静脈', '血管', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-13', '動脈と静脈の間にあり、細胞との間で酸素や養分などの受け渡しを行う細い血管を何というか。', '毛細血管', '血管', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-14', '赤血球に含まれ、酸素と結びついて酸素を運ぶ赤い色素を何というか。', 'ヘモグロビン', '血液成分', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-15', '病原体などを取り込んで分解する働きをもつ血液の成分を何というか。', '白血球', '血液成分', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-16', '出血したときに血液を固め、血を止める働きをする血液の成分を何というか。', '血小板', '血液成分', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-17', '血液の液体成分で、養分や二酸化炭素などを運ぶものを何というか。', '血しょう', '血液成分', '{"accept":["血漿","けっしょう"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-18', '心臓から肺へ血液を送り出す血管を何というか。', '肺動脈', '血管', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-19', '心臓の4つの部屋のうち、全身へ血液を送り出す部屋を何というか。', '左心室', '心臓', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kokyu-junkan', 'q-20', '全身から戻ってきた血液が、最初に入る心臓の部屋を何というか。', '右心房', '心臓', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-01', '細胞の活動で生じた不要な物質を、体外へ出す働きを何というか。', '排出', '排出', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-02', '細胞の呼吸で生じた二酸化炭素を、主に体外へ出す器官は何か。', '肺', '排出', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-03', '皮膚から水や塩分などを含む液体が体外へ出る現象を何というか。', '発汗', '排出', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-04', '発汗によって皮膚から体外へ出る液体を何というか。', '汗', '排出', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-05', '汗をつくって体外へ出す器官を何というか。', '汗腺', '排出', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-06', 'タンパク質が分解されたときに生じる、体にとって有害な物質を何というか。', 'アンモニア', '排出', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-07', '肝臓でアンモニアからつくられ、尿として体外へ排出される物質を何というか。', '尿素', '肝臓', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-08', 'アンモニアを、より害の少ない尿素に変える器官は何か。', '肝臓', '肝臓', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-09', '肝臓で、体に有害な物質を害の少ない物質に変える働きを何というか。', '解毒', '肝臓', '{"accept":["解毒作用"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-10', '肝臓で、余分なブドウ糖からつくられ、貯蔵される物質を何というか。', 'グリコーゲン', '肝臓', '{"accept":["グリコゲン"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-11', '血液中の尿素などの不要物をこし取り、尿をつくる器官は何か。', '腎臓', '腎臓', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-12', '腎臓でつくられ、尿素や余分な水分などを含む液体を何というか。', '尿', '腎臓', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-13', '腎臓で血液からこし取られた尿が一時的にためられる器官は何か。', '膀胱', '尿', '{"accept":["ぼうこう"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-14', '膀胱にたまった尿を体外へ運ぶ管を何というか。', '尿道', '尿', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-15', '腎臓から膀胱へ尿を運ぶ左右一対の管を何というか。', '輸尿管', '尿', '{"accept":["尿管"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-16', '血液中の尿素を腎臓へ運ぶ液体成分は何か。', '血しょう', '血液', '{"accept":["血漿","けっしょう"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-17', '腎臓で、血液から尿素などの不要物をこし取る働きを何というか。', 'ろ過', '腎臓', '{"accept":["濾過","ろか"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-haishutsu', 'q-18', '腎臓の働きによって、血液中の尿素の量は増えるか、減るか。', '減る', '腎臓', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-01', '光・音・温度など、動物が外界から受け取る変化を何というか。', '刺激', '刺激と反応', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-02', '刺激を受け取り、神経に信号を送る目や耳などの器官を何というか。', '感覚器官', '感覚器官', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-03', '光を刺激として受け取る感覚器官は何か。', '目', '感覚器官', '{"accept":["眼","め"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-04', '目の奥にあり、光の刺激を受け取る細胞がある部分を何というか。', '網膜', '目', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-05', '目に入る光を屈折させ、網膜に像を結ばせるレンズのような部分を何というか。', '水晶体', '目', '{"accept":["レンズ"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-06', '瞳孔の周りにあり、目に入る光の量を調節する部分を何というか。', '虹彩', '目', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-07', '虹彩の中央にある、光が目の中へ入る穴を何というか。', '瞳孔', '目', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-08', '音の刺激を受けると振動し、その振動を耳の奥へ伝える膜を何というか。', '鼓膜', '耳', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-09', '体の回転を感じ取る耳の器官を何というか。', '三半規管', '耳', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-10', '音の刺激によって生じた信号を脳へ伝える神経を何というか。', '聴神経', '耳', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-11', '感覚器官が受け取った刺激の信号を、脳や脊髄へ伝える神経を何というか。', '感覚神経', '神経', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-12', '脳や脊髄からの命令を、筋肉などへ伝える神経を何というか。', '運動神経', '神経', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-13', '脳と脊髄をまとめて何というか。', '中枢神経', '神経', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-14', '中枢神経と全身の感覚器官・運動器官をつなぐ神経を何というか。', '末しょう神経', '神経', '{"accept":["末梢神経","まっしょう神経","まっしょうしんけい"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-15', '脳の一部で、体の運動の調節や姿勢の保持に関わる部分を何というか。', '小脳', '脳', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-16', '熱いものに触れたとき、熱いと感じる前に手を引っ込めるような反応を何というか。', '反射', '反応', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-17', '反射の命令を出す中枢として働くことが多い器官は何か。', '脊髄', '反射', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-18', '刺激を受けたとき、感覚器官からの信号をもとに行動を判断する脳の部分を何というか。', '大脳', '脳', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-19', '神経からの命令を受けて、実際に収縮して体を動かす組織を何というか。', '筋肉', '反応', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shigeki-hannou', 'q-20', '光を受けたとき、瞳孔を小さくして目の中に入る光の量を減らす反応を何というか。', '瞳孔反射', '反射', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-01', '生物が自分と同じ種類の新しい個体をつくることを何というか。', '生殖', '生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-02', '1個体の親から、受精を行わずに子ができる生殖を何というか。', '無性生殖', '生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-03', '2個体の親がつくる生殖細胞の受精によって子ができる生殖を何というか。', '有性生殖', '生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-04', '有性生殖で、受精のためにつくられる細胞を何というか。', '生殖細胞', '生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-05', 'ヒトの男性がつくる生殖細胞を何というか。', '精子', 'ヒトの生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-06', 'ヒトの女性がつくる生殖細胞を何というか。', '卵', 'ヒトの生殖', '{"accept":["卵細胞"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-07', '精子と卵が結合することを何というか。', '受精', 'ヒトの生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-08', '受精によってできる最初の細胞を何というか。', '受精卵', 'ヒトの生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-09', 'ヒトの受精卵が細胞分裂を繰り返して成長する過程を何というか。', '発生', 'ヒトの生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-10', '精子をつくる男性の生殖器官を何というか。', '精巣', 'ヒトの生殖', '{"accept":["睾丸"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-11', '卵をつくる女性の生殖器官を何というか。', '卵巣', 'ヒトの生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-12', '体細胞が分裂して、同じ種類の細胞が2個できる細胞分裂を何というか。', '体細胞分裂', '細胞分裂', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-13', '細胞分裂のとき、核の中でひも状に見えるようになるものを何というか。', '染色体', '細胞分裂', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-14', '体細胞分裂によってできた2個の細胞の染色体数は、分裂前と比べてどうなるか。', '変わらない', '細胞分裂', '{"accept":["同じ"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-15', 'アメーバのように、1個体が2つに分かれてふえる無性生殖を何というか。', '分裂', '無性生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-16', 'ヒドラの体にできた芽が成長して新しい個体になる無性生殖を何というか。', '出芽', '無性生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seishoku', 'q-17', 'ジャガイモのいもやオランダイチゴの茎のように、植物の体の一部から新しい個体ができる無性生殖を何というか。', '栄養生殖', '無性生殖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-01', '親から子へ伝わる、形や性質などの特徴を何というか。', '形質', '遺伝', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-02', '親の形質が子に伝わる現象を何というか。', '遺伝', '遺伝', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-03', '染色体にあり、形質を決めるもとになる情報を何というか。', '遺伝子', '遺伝子', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-04', '遺伝子の本体である物質を何というか。', 'DNA', '遺伝子', '{"accept":["デオキシリボ核酸","ディーエヌエー"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-05', '遺伝子を含み、細胞分裂のときに核の中でひも状に見えるものを何というか。', '染色体', '遺伝子', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-06', '遺伝の規則性を調べるため、親どうしをかけ合わせることを何というか。', '交配', '交配実験', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-07', 'メンデルが遺伝の実験に用いた植物は何か。', 'エンドウ', '交配実験', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-08', '代々、自家受粉を繰り返しても同じ形質が現れる個体を何というか。', '純系', '交配実験', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-09', '2つの異なる形質をもつ純系を交配したとき、子に現れやすい形質を何というか。', '顕性形質', '遺伝の規則性', '{"accept":["優性形質"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-10', '2つの異なる形質をもつ純系を交配したとき、子に現れにくく、孫の代などで現れる形質を何というか。', '潜性形質', '遺伝の規則性', '{"accept":["劣性形質"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-11', '顕性形質と潜性形質のように、対になっている形質を何というか。', '対立形質', '遺伝の規則性', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-12', '純系の顕性形質をもつ親と純系の潜性形質をもつ親を交配したときにできる子の代を何というか。', 'F1', '交配実験', '{"accept":["F₁","第一世代","子の代","子","子世代"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-13', 'F1どうしを交配したときにできる孫の代を何というか。', 'F2', '交配実験', '{"accept":["F₂","第二世代","孫の代","孫","孫世代"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-14', '生殖細胞がつくられるとき、対になった遺伝子が分かれて別々の生殖細胞に入る法則を何というか。', '分離の法則', '遺伝の規則性', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-15', '有性生殖で、生殖細胞をつくるときに行われる、染色体数を半分にする細胞分裂を何というか。', '減数分裂', '細胞分裂', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-16', '顕性形質をAA、潜性形質をaaで表すとき、Aaのように異なる遺伝子をもつ個体に現れる形質は何か。', '顕性形質', '遺伝の規則性', '{"accept":["優性形質"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-17', 'Aaどうしを交配したとき、子に現れる顕性形質と潜性形質の割合は何対何か。', '3対1', '交配実験', '{"accept":["3:1","3：1"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-18', 'Aaどうしを交配したとき、潜性形質が現れる個体の割合は何分の何か。', '4分の1', '交配実験', '{"accept":["1/4","4ぶんの1","25%"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-iden', 'q-19', '無性生殖でできた子は、親と同じ遺伝子をもつため、親との形質の違いが有性生殖より何か。', '少ない', '遺伝', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-01', '生物が長い時間をかけて、世代を重ねるうちに形や性質を変化させることを何というか。', '進化', '進化', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-02', '現在の生物が、長い時間をかけて変化してきたことを示す証拠の一つで、過去の生物の体や活動のあとを何というか。', '化石', '進化の証拠', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-03', '地層の中で、下にある地層は上にある地層と比べて、一般に新しいか古いか。', '古い', '地層', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-04', '地層が堆積した当時の地質時代を知る手がかりになる化石を何というか。', '示準化石', '化石', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-05', '示準化石に適しているのは、広い地域に分布し、生存していた期間が長い生物と短い生物のどちらか。', '短い', '化石', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-06', '地層が堆積した当時の環境を知る手がかりになる化石を何というか。', '示相化石', '化石', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-07', '示相化石になる生物が分布する地域は、広いか狭いか。', '狭い', '化石', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-08', '始祖鳥は、は虫類とどの動物の両方の特徴をもつ化石生物か。', '鳥類', '化石', '{"accept":["鳥"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-09', '人間の腕、コウモリの翼、クジラのひれのように、基本的なつくりが共通している器官を何というか。', '相同器官', '進化の証拠', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-10', '相同器官があることは、これらの生物が共通の何から進化したことを示しているか。', '祖先', '進化の証拠', '{"accept":["共通祖先"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-11', '生物の体にあるが、現在はほとんど働いていない器官を何というか。', '痕跡器官', '進化の証拠', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-12', 'ヒトの尾てい骨は、どの器官の痕跡と考えられているか。', '尾', '痕跡器官', '{"accept":["しっぽ","尻尾"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-13', '生物が生活する環境に適した形や性質をもつようになることを何というか。', '適応', '進化', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-14', '地球の歴史を、生物や地層の変化に基づいて区分した時代を何というか。', '地質時代', '地質時代', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-15', '古生代の初めに現れ、古生代の終わりに絶滅した代表的な示準化石を何というか。', '三葉虫', '化石', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-shinka', 'q-16', '中生代の代表的な示準化石で、現在は絶滅している頭足類を何というか。', 'アンモナイト', '化石', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-01', 'ある地域に生息する生物と、それを取り巻く環境を一つのまとまりとして何というか。', '生態系', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-02', '生態系を構成する要素のうち、植物や動物などの生物に関する環境を何というか。', '生物的環境', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-03', '生態系を構成する要素のうち、光・温度・水・空気などの生物以外の環境を何というか。', '非生物的環境', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-04', '光合成によって無機物から有機物をつくる生物を何というか。', '生産者', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-05', '他の生物を食べて有機物を取り入れる生物を何というか。', '消費者', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-06', '生物の死がいや排出物を分解し、無機物に戻す生物を何というか。', '分解者', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-07', '生物どうしの「食べる・食べられる」という関係が、鎖のようにつながったものを何というか。', '食物連鎖', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-08', '複数の食物連鎖が網の目のようにつながったものを何というか。', '食物網', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-09', '食物連鎖で、生産者を直接食べる消費者を何というか。', '一次消費者', '食物連鎖', '{"accept":["第一次消費者"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-10', '食物連鎖で、植物を食べる動物を何というか。', '草食動物', '食物連鎖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-11', '食物連鎖で、他の動物を食べる動物を何というか。', '肉食動物', '食物連鎖', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-12', '生態系において、生物が生きるためのエネルギーの主なもとは何か。', '太陽光', 'エネルギー', '{"accept":["日光","太陽","太陽のエネルギー"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-13', '食物連鎖を通って、生物から生物へ受け渡されるものは何か。', 'エネルギー', 'エネルギー', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-14', '生態系の中で、エネルギーが生物から生物へ移動する流れを何というか。', 'エネルギーの流れ', 'エネルギー', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-15', '植物の光合成によって、空気中から取り入れられる物質は何か。', '二酸化炭素', '物質循環', '{"accept":["炭酸ガス","CO2"]}');
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-16', '植物の光合成によって、空気中へ放出される気体は何か。', '酸素', '物質循環', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-17', '生産者・消費者・分解者の働きによって、物質が生態系の中を繰り返し移動することを何というか。', '物質循環', '物質循環', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-seitaikei', 'q-18', '生態系の中で、生物の種類や数の関係が大きく変化せずに保たれている状態を何というか。', 'つり合い', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-01', '生物の種類、同じ種類の個体の形質、生態系の多様さなど、生物に見られるさまざまな違いを何というか。', '生物多様性', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-02', 'ある地域に生息する、同じ種類の生物の集まりを何というか。', '個体群', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-03', 'ある地域に生息する、さまざまな種類の生物の集まりを何というか。', '生物群集', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-04', 'ある地域の生物群集と、それを取り巻く環境を合わせたまとまりを何というか。', '生態系', '生態系', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-05', 'もともとその地域にいなかったのに、人間の活動によって持ち込まれた生物を何というか。', '外来種', '生物多様性', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-06', '絶滅するおそれがある生物の種類を何というか。', '絶滅危惧種', '生物多様性', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-07', 'その種類の生物が地球上から一個体もいなくなることを何というか。', '絶滅', '生物多様性', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-08', '絶滅のおそれがある生物の生息状況などをまとめた資料を何というか。', 'レッドデータブック', '生物多様性', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-09', '道路や都市の開発などによって、生物が生活する場所が失われることを何というか。', '生息地破壊', '環境問題', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-10', '生物の種類や生態系を守り、将来にわたって維持することを何というか。', '環境保全', '環境保全', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-11', '生物やその生息地を守るために、開発などを制限して保護する地域を何というか。', '自然保護区', '環境保全', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-12', '海や川などに有害物質やごみが入り、水質が悪化することを何というか。', '水質汚濁', '環境問題', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-13', '工場の排煙や自動車の排出ガスなどによって、空気が汚れることを何というか。', '大気汚染', '環境問題', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-14', '川や湖に窒素やリンを含む物質が流れ込み、植物プランクトンなどが増えすぎる現象を何というか。', '富栄養化', '環境問題', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-15', '海や沿岸で植物プランクトンが異常に増殖し、水の色が赤褐色などに変わる現象を何というか。', '赤潮', '環境問題', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-16', '湖や池で、藍藻類などが大量に増殖して水面が緑色になる現象を何というか。', 'アオコ', '環境問題', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-17', '生物の体内に取り込まれた有害物質が、食物連鎖の上位ほど濃くなる現象を何というか。', '生物濃縮', '環境問題', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-18', '大気中の二酸化炭素などが地表から出る熱を吸収する働きを何というか。', '温室効果', '地球環境', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-19', '温室効果が強まり、地球全体の平均気温が上昇することを何というか。', '地球温暖化', '地球環境', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-20', '成層圏にあり、生物に有害な紫外線を吸収する層を何というか。', 'オゾン層', '地球環境', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-21', '環境を守りながら資源を利用し、将来の世代も利用できるようにする考え方を何というか。', '持続可能性', '環境保全', NULL);
INSERT OR IGNORE INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kankyou', 'q-22', '開発を行う前に、環境への影響を調査・予測・評価することを何というか。', '環境アセスメント', '環境保全', '{"accept":["環境影響評価"]}');
