-- 0021: 化学クイズ9件と問題161件を本番DBに追加する。
-- 適用: npx wrangler d1 execute chishiki-quiz-db --remote --file=./migrations/0021_add_kagaku_quizzes.sql
-- 冪等ではない: 同じデータが存在するDBには2回適用しないこと。

INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-01', '物質の性質と状態変化', 'rika', '化学', 'rika/kagaku-01/', 10, 400, 0);
INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-02', '気体の発生と性質', 'rika', '化学', 'rika/kagaku-02/', 10, 410, 0);
INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-03', '水溶液', 'rika', '化学', 'rika/kagaku-03/', 10, 420, 0);
INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-04', '物質の成り立ち', 'rika', '化学', 'rika/kagaku-04/', 10, 430, 0);
INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-05', '化学変化と化学反応式', 'rika', '化学', 'rika/kagaku-05/', 10, 440, 0);
INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-06', '酸化・還元と質量', 'rika', '化学', 'rika/kagaku-06/', 10, 450, 0);
INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-07', 'イオンと中和', 'rika', '化学', 'rika/kagaku-07/', 10, 460, 0);
INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-08', '化学変化と電池・電気分解', 'rika', '化学', 'rika/kagaku-08/', 10, 470, 0);
INSERT INTO quizzes (id, name, genre, section, url, max_score, sort_order, is_archived) VALUES ('rika-kagaku-09', '有機物・無機物と物質の分類', 'rika', '化学', 'rika/kagaku-09/', 10, 480, 0);

INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-01', '物質1 cm³あたりの質量を何というか。', '密度', '物質の性質', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-02', '金属の表面に見られる特有の光沢を何というか。', '金属光沢', '金属の性質', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-03', '電気を通しやすい性質を何というか。', '導電性', '金属の性質', '{"accept":["電気伝導性"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-04', '金属を引っ張って細い線にのばすことができる性質を何というか。', '延性', '金属の性質', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-05', '金属をたたいて薄い板に広げることができる性質を何というか。', '展性', '金属の性質', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-06', '温度を変えることで、物質が固体・液体・気体の間で変わることを何というか。', '状態変化', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-07', '一定の形と一定の体積をもつ物質の状態を何というか。', '固体', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-08', '一定の体積をもつが、容器に応じて形を変える物質の状態を何というか。', '液体', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-09', '一定の形も体積もなく、容器いっぱいに広がる物質の状態を何というか。', '気体', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-10', '固体が液体に変わる状態変化を何というか。', '融解', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-11', '液体が固体に変わる状態変化を何というか。', '凝固', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-12', '液体が気体に変わる状態変化を何というか。', '気化', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-13', '気体が液体に変わる状態変化を何というか。', '凝縮', '状態変化', '{"accept":["液化"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-14', '液体内部からも気体が発生し、液体全体で気化が起こる現象を何というか。', '沸騰', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-15', '固体が液体に変わり始める温度を何というか。', '融点', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-16', '液体が沸騰を始める温度を何というか。', '沸点', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-17', '固体が液体を経ずに直接気体に変わる状態変化を何というか。', '昇華', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-18', '状態変化のとき、質量と体積のうち変化しないのはどちらか。', '質量', '状態変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-19', '液体の混合物を、沸点の違いを利用して分ける方法を何というか。', '蒸留', '物質の分離', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-20', '密度は、物質の質量を何で割って求めるか。', '体積', '物質の性質', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-21', '液体の体積をはかるときに使う、細長い円筒形の器具は何か。', 'メスシリンダー', '実験器具', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-22', '液体を加熱するとき、急な沸騰を防ぐために入れるものは何か。', '沸騰石', '実験器具', '{"accept":["ふっとう石"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-01', 'q-23', '水とエタノールの混合物を蒸留すると、先に多く出てくるのはどちらか。', 'エタノール', '物質の分離', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-01', '水に溶けにくい気体を、水を押しのけて集める方法を何というか。', '水上置換法', '気体の集め方', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-02', '空気より重く、水に溶けやすい気体を集める方法を何というか。', '下方置換法', '気体の集め方', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-03', '空気より軽く、水に溶けやすい気体を集める方法を何というか。', '上方置換法', '気体の集め方', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-04', '火のついた線香を入れると、線香が激しく燃える気体は何か。', '酸素', '酸素', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-05', '石灰水を白くにごらせる気体は何か。', '二酸化炭素', '二酸化炭素', '{"accept":["炭酸ガス"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-06', '火を近づけると「ポン」という音を立てて燃える気体は何か。', '水素', '水素', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-07', '湿らせた赤色リトマス紙を青色に変える、刺激臭のある気体は何か。', 'アンモニア', 'アンモニア', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-08', '二酸化マンガンのように、自身は変化せず化学変化を速くする物質を何というか。', '触媒', '酸素', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-09', '過酸化水素水から酸素を発生させる実験で、触媒として加える黒色の物質は何か。', '二酸化マンガン', '酸素', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-10', '石灰石や貝殻の主成分にうすい塩酸を加えると発生する気体は何か。', '二酸化炭素', '二酸化炭素', '{"accept":["炭酸ガス"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-11', '亜鉛にうすい塩酸を加えると発生する気体は何か。', '水素', '水素', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-14', 'アンモニアを水に溶かした水溶液を何というか。', 'アンモニア水', 'アンモニア', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-15', '二酸化炭素を水に溶かした水溶液を何というか。', '炭酸水', '二酸化炭素', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-16', '水素を燃やしたときにできる物質は何か。', '水', '水素', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-02', 'q-18', '空気中に最も多く含まれる気体は何か。', '窒素', '空気', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-01', '物質が水に溶けてできた、均一な液体を何というか。', '水溶液', '水溶液', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-02', '水溶液で、水に溶けている物質を何というか。', '溶質', '水溶液', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-03', '水溶液で、溶質を溶かしている液体を何というか。', '溶媒', '水溶液', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-04', '物質が水に溶けて水溶液になる現象を何というか。', '溶解', '水溶液', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-05', '一定の温度で、水100 gに溶けることができる物質の最大の質量を何というか。', '溶解度', '溶解度', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-06', 'ある温度で、溶質がそれ以上溶けないまで溶けている水溶液を何というか。', '飽和水溶液', '溶解度', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-07', '溶解度が「20 g」と示されているとき、その物質が溶ける水の質量は何 g か。', '100', '溶解度', '{"accept":["100g","100 g"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-08', '水に溶けずに残った固体と液体を分ける方法を何というか。', 'ろ過', '分離', '{"accept":["濾過"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-10', 'ろ過したとき、ろ紙を通り抜けた液体を何というか。', 'ろ液', '分離', '{"accept":["濾液"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-11', '水溶液を冷やしたり、水を蒸発させたりして、溶質を固体として取り出したときにできる固体を何というか。', '結晶', '結晶', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-12', '温度による溶解度の違いを利用して、結晶を取り出しながら物質をきれいにする方法を何というか。', '再結晶', '結晶', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-13', '水溶液から溶質を取り出すため、水を加熱して気体に変えることを何というか。', '蒸発', '分離', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-14', '水溶液全体の質量に対する溶質の質量の割合を百分率で表したものを何というか。', '質量パーセント濃度', '濃度', '{"accept":["質量百分率"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-15', '食塩水100 gに食塩が5 g溶けているとき、質量パーセント濃度は何 %か。', '5', '濃度', '{"accept":["5%","5 %"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-16', '一般に、固体の物質は水の温度が高くなると溶解度がどうなることが多いか。', '大きくなる', '溶解度', '{"accept":["増える","増加する","上がる"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-17', '気体の物質は、水の温度が高くなると溶解度がどうなることが多いか。', '小さくなる', '溶解度', '{"accept":["減る","減少する","下がる"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-18', '溶質が溶媒に溶けた液全体を何というか。', '溶液', '水溶液', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-19', '温度と溶解度の関係を表したグラフを何というか。', '溶解度曲線', '溶解度', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-03', 'q-21', 'ろ過をするとき、液を伝わらせて注ぐために使う器具は何か。', 'ガラス棒', '分離', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-01', '物質をつくるもとになる、これ以上化学的に分けられない基本の粒子を何というか。', '原子', '原子・分子', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-02', '原子の種類のことを何というか。', '元素', '原子・分子', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-03', '物質を構成する粒子のうち、複数の原子が結びついてできたものを何というか。', '分子', '原子・分子', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-04', '元素をアルファベット1文字または2文字で表した記号を何というか。', '元素記号', '元素', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-05', '物質を、元素記号と数字を用いて表したものを何というか。', '化学式', '化学式', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-06', '1種類の元素だけからできている物質を何というか。', '単体', '物質の分類', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-07', '2種類以上の元素からできている物質を何というか。', '化合物', '物質の分類', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-08', '水素の元素記号は何か。', 'H', '元素記号', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-09', '酸素の元素記号は何か。', 'O', '元素記号', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-10', '炭素の元素記号は何か。', 'C', '元素記号', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-11', '窒素の元素記号は何か。', 'N', '元素記号', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-12', '鉄の元素記号は何か。', 'Fe', '元素記号', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-13', '水の化学式は何か。', 'H2O', '化学式', '{"accept":["Ｈ₂Ｏ"],"explanation":"H2Oは、水素原子2個と酸素原子1個からなる。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-14', '酸素の化学式は何か。', 'O2', '化学式', '{"accept":["Ｏ₂"],"explanation":"O2は、酸素原子2個が結びついた分子を表す。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-15', '水素の化学式は何か。', 'H2', '化学式', '{"accept":["Ｈ₂"],"explanation":"H2は、水素原子2個が結びついた分子を表す。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-16', '二酸化炭素の化学式は何か。', 'CO2', '化学式', '{"accept":["ＣＯ₂"],"explanation":"CO2は、炭素原子1個と酸素原子2個からなる。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-17', '食塩（塩化ナトリウム）の化学式は何か。', 'NaCl', '化学式', '{"accept":["ＮａＣｌ"],"explanation":"NaClは、ナトリウムと塩素が1対1で結びついていることを表す。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-18', '2種類以上の物質が混じり合ったものを何というか。', '混合物', '物質の分類', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-19', '1種類の物質だけからできているものを何というか。', '純物質', '物質の分類', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-20', '銅の元素記号は何か。', 'Cu', '元素記号', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-21', 'マグネシウムの元素記号は何か。', 'Mg', '元素記号', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-04', 'q-22', 'ナトリウムの元素記号は何か。', 'Na', '元素記号', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-01', '物質が別の物質に変わる変化を何というか。', '化学変化', '化学変化', '{"accept":["化学反応"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-02', '1種類の物質が2種類以上の物質に分かれる化学変化を何というか。', '分解', '化学変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-03', '2種類以上の物質が結びついて別の物質になる化学変化を何というか。', '化合', '化学変化', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-06', '化学変化を化学式と記号を使って表した式を何というか。', '化学反応式', '化学反応式', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-07', '水に電流を流して分解すると発生する、火を近づけると燃える気体は何か。', '水素', '分解', '{"explanation":"水の電気分解は 2H2O → 2H2 + O2。陰極では水素が発生する。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-08', '水に電流を流して分解すると発生する、ものを燃やす働きを助ける気体は何か。', '酸素', '分解', '{"explanation":"水の電気分解は 2H2O → 2H2 + O2。陽極では酸素が発生する。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-09', '水の電気分解で、同じ温度・圧力で発生する水素と酸素の体積比は何対何か。', '2対1', '分解', '{"accept":["2:1","2：1"],"explanation":"2H2O → 2H2 + O2 より、同温・同圧での水素：酸素の体積比は2：1。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-10', '炭酸水素ナトリウムを加熱したときにできる、石灰水を白くにごらせる気体は何か。', '二酸化炭素', '分解', '{"accept":["炭酸ガス"],"explanation":"2NaHCO3 → Na2CO3 + H2O + CO2。発生する二酸化炭素は石灰水を白くにごらせる。"}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-11', '鉄と硫黄を加熱してできる黒色の物質は何か。', '硫化鉄', '化合', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-12', 'マグネシウムを燃やしたときにできる白色の物質は何か。', '酸化マグネシウム', '化合', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-16', '化学反応式で、左右の式の原子の数をそろえるためそれぞれの物質の前につける数字を何というか。', '係数', '化学反応式', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-17', '炭酸水素ナトリウムを加熱したときに、試験管に残る白色の固体は何か。', '炭酸ナトリウム', '分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-18', '水ができたことを確かめるために使う紙を何というか。', '塩化コバルト紙', '分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-19', '青色の塩化コバルト紙は、水にふれると何色に変わるか。', '赤色', '分解', '{"accept":["桃色","うすい赤色"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-05', 'q-20', '酸化銀を加熱すると、酸素のほかに何ができるか。', '銀', '分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-01', '物質が酸素と結びつく化学変化を何というか。', '酸化', '酸化・還元', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-02', '酸化物から酸素を取り去る化学変化を何というか。', '還元', '酸化・還元', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-03', '物質が酸素と激しく結びつき、光や熱を出す現象を何というか。', '燃焼', '酸化・還元', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-04', '鉄が空気中の酸素や水とゆっくり酸化してできる赤褐色の物質を何というか。', 'さび', '酸化・還元', '{"accept":["錆"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-05', '酸化銅と炭素を加熱したとき、酸化銅から酸素を奪う物質は何か。', '炭素', '酸化・還元', '{"accept":["C"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-06', '酸化銅を炭素で還元してできる赤色の金属は何か。', '銅', '酸化・還元', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-07', '化学変化の前後で、反応に関わる物質全体の質量が変わらないことを何というか。', '質量保存の法則', '化学変化と質量', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-08', '物質が酸素と結びついてできた物質を何というか。', '酸化物', '酸化・還元', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-10', '銅を加熱したときにできる黒色の物質は何か。', '酸化銅', '酸化・還元', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-11', '化学変化で周囲に熱を出す反応を何というか。', '発熱反応', '化学変化と熱', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-12', '化学変化で周囲から熱を吸収する反応を何というか。', '吸熱反応', '化学変化と熱', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-13', '炭素と酸素が化合して二酸化炭素になる反応は、発熱反応と吸熱反応のどちらか。', '発熱反応', '化学変化と熱', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-06', 'q-14', '水酸化ナトリウム水溶液と塩酸を混ぜる反応で、周囲の温度が上がる原因となる反応を何というか。', '中和', '化学変化と熱', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-01', '原子が電子を失ったり受け取ったりして、電気を帯びた粒子を何というか。', 'イオン', 'イオン', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-02', '正の電気を帯びたイオンを何というか。', '陽イオン', 'イオン', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-03', '負の電気を帯びたイオンを何というか。', '陰イオン', 'イオン', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-04', '水に溶けたとき、イオンに分かれて電流を通す物質を何というか。', '電解質', 'イオン', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-05', '電解質が水に溶けてイオンに分かれることを何というか。', '電離', 'イオン', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-06', '酸性の水溶液で、水酸化物イオンより多く含まれる陽イオンは何か。', '水素イオン', '酸・アルカリ', '{"accept":["H+"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-07', 'アルカリ性の水溶液で、水素イオンより多く含まれる陰イオンは何か。', '水酸化物イオン', '酸・アルカリ', '{"accept":["OH-"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-08', '水に溶けて水素イオンを生じる物質を何というか。', '酸', '酸・アルカリ', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-09', '水に溶けて水酸化物イオンを生じる物質を何というか。', 'アルカリ', '酸・アルカリ', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-10', '酸性・中性・アルカリ性の程度を0から14の数値で表したものを何というか。', 'pH', '酸・アルカリ', '{"accept":["ピーエイチ"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-11', '酸性で黄色、アルカリ性で青色、中性で緑色を示す指示薬を何というか。', 'BTB溶液', '指示薬', '{"accept":["BTB"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-12', '酸性で無色、アルカリ性で赤色を示す指示薬を何というか。', 'フェノールフタレイン溶液', '指示薬', '{"accept":["フェノールフタレイン"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-13', '酸とアルカリを混ぜ、それぞれの性質を打ち消し合う反応を何というか。', '中和', '中和', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-14', '中和で、水素イオンと水酸化物イオンが結びついてできる物質は何か。', '水', '中和', '{"accept":["H2O"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-15', '中和で、酸の陰イオンとアルカリの陽イオンが結びついてできる物質を何というか。', '塩', '中和', '{"accept":["えん"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-16', '塩酸と水酸化ナトリウム水溶液を中和させてできる塩は何か。', '塩化ナトリウム', '中和', '{"accept":["食塩"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-17', '酸性の水溶液に青色リトマス紙を入れたときの色は何色か。', '赤色', '指示薬', '{"accept":["赤"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-18', 'アルカリ性の水溶液に赤色リトマス紙を入れたときの色は何色か。', '青色', '指示薬', '{"accept":["青"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-19', '原子の中心にあり、正の電気をもつ粒を何というか。', '原子核', '原子の構造', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-20', '原子核のまわりにあり、負の電気をもつ粒を何というか。', '電子', '原子の構造', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-21', '原子が電子を失うと、陽イオンと陰イオンのどちらになるか。', '陽イオン', '原子の構造', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-22', '水に溶けてもイオンに分かれず、電流を通さない物質を何というか。', '非電解質', 'イオン', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-23', '塩酸という水溶液に溶けている物質は何か。', '塩化水素', '酸・アルカリ', '{"accept":["HCl"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-07', 'q-24', '酸性の水溶液にマグネシウムなどの金属を入れると発生する気体は何か。', '水素', '酸・アルカリ', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-01', '化学変化によって電気エネルギーを取り出す装置を何というか。', '電池', '化学変化と電池', '{"accept":["化学電池"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-02', '電池で、電子を放出する電極を何というか。', '負極', '電池', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-03', '電池で、電子を受け取る電極を何というか。', '正極', '電池', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-04', '電流を流して、物質を分解したり別の物質を生じさせたりする化学変化を何というか。', '電気分解', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-05', '電気分解で、電源装置の正極につながる電極を何というか。', '陽極', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-06', '電気分解で、電源装置の負極につながる電極を何というか。', '陰極', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-07', '水酸化ナトリウムを少量加えた水に電流を流して分解したとき、陰極で発生する気体は何か。', '水素', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-08', '水酸化ナトリウムを少量加えた水に電流を流して分解したとき、陽極で発生する気体は何か。', '酸素', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-09', '炭素電極を用いて塩化銅水溶液を電気分解したとき、陰極に付着する赤色の金属は何か。', '銅', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-10', '炭素電極を用いて塩化銅水溶液を電気分解したとき、陽極で発生する黄緑色の気体は何か。', '塩素', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-11', '金属が電子を失って陽イオンになる変化を何というか。', '酸化', '電池', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-12', '金属イオンが電子を受け取って金属になる変化を何というか。', '還元', '電池', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-13', '銅イオンを含む水溶液に鉄を入れると、鉄の表面に付着する金属は何か。', '銅', '金属イオン', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-14', '銅イオンを含む水溶液に鉄を入れると、鉄は何イオンになって水溶液中へ溶け出すか。', '鉄イオン', '金属イオン', '{"accept":["Fe2+"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-15', '水素と酸素を反応させて電気エネルギーを取り出す電池を何というか。', '燃料電池', '電池', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-16', '燃料電池で、水素と酸素が反応してできる物質は何か。', '水', '電池', '{"accept":["H2O"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-17', 'うすい塩酸を電気分解したとき、陰極で発生する気体は何か。', '水素', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-08', 'q-18', 'うすい塩酸を電気分解したとき、陽極で発生する気体は何か。', '塩素', '電気分解', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-01', '炭素を含む化合物のうち、二酸化炭素・一酸化炭素・炭酸塩などを除いたものを何というか。', '有機物', '物質の分類', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-02', '有機物以外の物質を何というか。', '無機物', '物質の分類', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-03', '炭素の単体のうち、黒色でやわらかく、紙にこすると黒い跡がつき、電気を通すものは何か。', '黒鉛', '非金属', '{"accept":["グラファイト"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-04', '鉄、銅、アルミニウムのように、特有の光沢や導電性をもつ物質を何というか。', '金属', '物質の分類', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-05', '硫黄や炭素のように、金属ではない物質を何というか。', '非金属', '物質の分類', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-07', '石灰石や大理石の主成分である物質は何か。', '炭酸カルシウム', '無機物', '{"accept":["CaCO3"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-08', '石油などを原料として人工的につくられることが多い有機物の総称を何というか。', 'プラスチック', '有機物', '{"accept":["合成樹脂"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-09', '紙や木、砂糖、ろうそくなどに共通して含まれる元素は何か。', '炭素', '有機物', '{"accept":["C"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-10', '砂糖などの有機物を完全に燃やしたときに発生する気体は何か。', '二酸化炭素', '有機物', '{"accept":["炭酸ガス","CO2"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-11', '砂糖などの有機物を完全に燃やしたとき、二酸化炭素とともに生じる物質は何か。', '水', '有機物', '{"accept":["H2O"]}');
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-12', '有機物を燃やして二酸化炭素が出たことを確かめるために使う液体は何か。', '石灰水', '有機物', NULL);
INSERT INTO items (quiz_id, item_key, label, answer, category, extra_json) VALUES ('rika-kagaku-09', 'q-13', '砂糖と食塩を加熱したとき、黒くこげるのはどちらか。', '砂糖', '有機物', NULL);
